import Link from "next/link";
import { notFound } from "next/navigation";
import { ProjectShell } from "@/components/project-shell";
import { getProject } from "@/lib/projects";
export default async function PrivacyPage({params}:{params:Promise<{projectSlug:string}>}){const {projectSlug}=await params;const project=getProject(projectSlug);if(!project)notFound();return <ProjectShell project={project}><article className="mx-auto max-w-4xl px-5 py-10 md:px-8 md:py-14"><Link href={`/${project.slug}`} className="text-sm font-bold text-[var(--project-primary)] hover:underline">← Back to the letter tool</Link><h1 className="mt-6 text-4xl font-bold text-[var(--project-dark)]">Privacy statement</h1><div className="mt-8 space-y-7 rounded-3xl bg-white p-7 leading-7 shadow-sm ring-1 ring-black/5 md:p-10">
<section><h2 className="text-xl font-bold">Who is responsible for your information?</h2><p className="mt-2"><strong>{project.dataController}</strong> is the Data Controller. <strong>{project.dataProcessor}</strong> acts as Data Processor for this tool.</p></section>
<section><h2 className="text-xl font-bold">What we collect</h2><p className="mt-2">We collect your name, email address, postal address and postcode, the project points you choose, whether you add a comment, whether you opt in to project updates, the action you take in the tool, and limited first-party source information such as UTM campaign parameters. We also create a one-way hash of technical information for basic abuse prevention; the raw IP address is not stored.</p></section>
<section><h2 className="text-xl font-bold">Why we use it</h2><p className="mt-2">The information is used to operate the representation tool, understand levels and themes of support, protect the dataset from obvious duplicate or abusive activity, and prepare project reporting. Aggregated or anonymised insight may be shared with {project.planningAuthority.name}. Your personal information is not published by this tool.</p></section>
<section><h2 className="text-xl font-bold">Lawful basis</h2><p className="mt-2">For the core operation of the tool, {project.dataController} relies on <strong>{project.privacy.coreLawfulBasis}</strong>{project.privacy.legitimateInterest?`, specifically its interest in ${project.privacy.legitimateInterest}`:""}. The separate email update option relies on your consent and is unticked by default.</p></section>
<section><h2 className="text-xl font-bold">Sending your representation</h2><p className="mt-2">This website does not send a planning representation on your behalf. “Open in Email” opens your own email application with a draft addressed to the planning authority. You remain in control and must choose whether to send it. Using this tool does not add you to a mailing list unless you separately opt in.</p></section>
<section><h2 className="text-xl font-bold">Retention and your rights</h2><p className="mt-2">Project records are configured for a retention period of {project.retentionMonths} months after the project consultation closing date where one is set. You can exercise your data protection rights by contacting the Data Controller{project.privacy.contactEmail?` at ${project.privacy.contactEmail}`:" through the project's published contact route"}.</p></section>
</div></article></ProjectShell>;}
